### ISSUE TITLE
feat: impelement figma desgin for sign up - dev

### ISSUE THREAD

**Issue by Amrhub** [Amrhub/healthCare-source#5]
- [x] create landing page for guest to match [this Figma Design](https://www.figma.com/file/n5p1Y3WR1VstxSlv1dSmlI/Final-High-Wireframe?node-id=184%3A66)
- [x] sign up should be a pop window 
- [x] sign up should close when user `X` button, clicks outside pop up, or tap `ESC` button 
[Sign up pop window - Figma design](https://www.figma.com/file/n5p1Y3WR1VstxSlv1dSmlI/Final-High-Wireframe?node-id=10%3A83)

**Comment by mohamedadelyousryali** [comment]
- [ ] This distance is very large
![image](https://user-images.githubusercontent.com/60586513/147850142-638eb525-1baa-474b-b6f7-ac71eaabb982.png)
